[build]
  command = "npm install && npm run build"  # Asegúrate de tener un script de build si es necesario
  publish = "dist"  # El directorio para la salida (si existe uno)

# Directorio de funciones (si las funciones de Netlify están en netlify/functions)
[functions]
  directory = "netlify/functions"

# Configuración de funciones de tiempo de espera
[functions."*"]
  timeout = 10

# Configuración de encabezados CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Origin = "*"

# Redirecciones si es necesario
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/auth/:splat"
  status = 200
