[build]
  command = "npm run build"  # Ejecutará el comando npm run build, que en tu caso solo imprimirá un mensaje
  publish = "."  # Publica el directorio raíz (asegúrate de que tu backend esté allí)

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

