[build]
  command = "npm run build"  # Ejecutará el comando npm run build
  publish = "."  # Publica el directorio raíz

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true


