# Configuración de la construcción del proyecto
[build]
  command = "npm run build"  # Comando para construir el proyecto (ajustado según tu proyecto)
  publish = "public"  # Directorio de publicación (ajustar si es necesario)

# Configuración de los encabezados para CORS
[[headers]]
  for = "/api/*"  # Aplica para las rutas de las funciones backend
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Permite solicitudes desde cualquier dominio
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"  # Métodos permitidos
    Access-Control-Allow-Headers = "Content-Type, Authorization"  # Encabezados permitidos

# Redirecciones desde HTTP a HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Configuración para las funciones serverless de Netlify
[functions]
  directory = "netlify/functions"  # Directorio donde se encuentran las funciones serverless

  # Timeout de las funciones (especificar para cada función)
  [functions."*"]
    timeout = 10  # Timeout para las funciones (10 segundos)

# Redirección para la función de login (ajustar según las rutas de tus funciones)
[[headers]]
  for = "/.netlify/functions/login"  # Ruta de la función de login
  [headers.values]
    Access-Control-Allow-Origin = "https://test-sanear.netlify.app"  # Permite solicitudes desde este dominio
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"  # Métodos permitidos
    Access-Control-Allow-Headers = "Content-Type, Authorization"  # Encabezados permitidos

# Redirección para funciones de autenticación (si usas JWT o autenticación similar)
[[redirects]]
  from = "/auth/*"  # Ruta para las funciones de autenticación
  to = "/.netlify/functions/auth/:splat"  # Ruta donde se encuentran las funciones de autenticación
  status = 200