[build]
  # Solo instala dependencias, no necesitas un paso de construcción como en un frontend
  command = "npm install"
  publish = "netlify/functions"  # Netlify buscará las funciones dentro de este directorio
  
[functions]
  directory = "netlify/functions"  # Directorio de funciones serverless
  
  # Configuración del timeout para las funciones (si lo necesitas)
  [functions.timeout]
  seconds = 10  # Tiempo de espera para las funciones

  # Opcional: si tienes dependencias adicionales en tus funciones, puedes especificarlas aquí
  external_node_modules = ["googleapis", "jsonwebtoken"]  # Si usas estas dependencias en las funciones

# Configuración de los encabezados para CORS (si es necesario)
[[headers]]
  for = "/api/*"  # Aplica para las rutas de las funciones backend
  [headers.values]
    Access-Control-Allow-Origin = "*"  # Permite solicitudes desde cualquier dominio
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"  # Métodos permitidos
    Access-Control-Allow-Headers = "Content-Type, Authorization"  # Encabezados permitidos

[[redirects]]
  from = "/auth/*"  # Ruta para las funciones de autenticación
  to = "/.netlify/functions/auth/:splat"  # Ruta de las funciones
  status = 200

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true