[build]
  command = "npm run build"  # Comando que ejecuta la construcción
  publish = "dist/tu-nombre-del-proyecto"  # Cambia a tu carpeta de salida de construcción, generalmente `dist/<nombre-del-proyecto>`

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/.netlify/functions/login"
  [headers.values]
    Access-Control-Allow-Origin = "https://test-sanear.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
